motion:
  velocity: 100
  acc: 200

gripper:
  grasp_port: 1
  release_port: 2
  wait_time: 1.0

poses:

  home:
    type: joint
    position: [0.0, 0.0, 90.0, 0.0, 90.0, 0.0]
  
  pick:
    type: task
    position: [370.0, 5.0, 200.0, 5.0, 179.0, 5.0]

  place:
    type: task
    position: [550.0, 4.0, 150.0, 5.0, 179.0, 5.0]

  start:
    type: task
    position: [448.74, -29.4, 52.58, 35.86, -179.89, -57.19]

  a:
    type: task
    position: [448.74, -29.4, 86.15, 35.86, -179.89, -57.19]

  b:
    type: task
    position: [560.9, -23.31, 51.58, 163.69, -179.74, 70.37]

  c:
    type: task
    position: [529.19, -21.85, 49.31, 160.91, -179.54, 67.7]

  d:
    type: task
    position: [590.09, -20.84, 49.65, 161.63, -179.36, 68.28]
    
  frame_pick:
    type: task
    position: [370.0, 5.0, 200.0, 5.0, 179.0, 5.0]

  frame_place:
    type: task
    position: [550.0, 4.0, 200.0, 5.0, 179.0, 5.0]
    
  pin_pick:
    type: task
    position: [370.0, 5.0, 37.6, 5.0, 179.0, 5.0]
    
  pin_place:
    type: task
    position: [550.0, 4.0, 200.0, 5.0, 179.0, 5.0]
